import type { Metadata } from "next";
import "./globals.css";

import { ThemeProvider } from "../../components/ThemeProvider";
import SidebarWrapper from "../../components/SidebarWrapper";
import NavbarWrapper from "../../components/NavbarWrapper";
import ContentWrapper from "../../components/ContentWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className="min-h-screen"
        style={{
          background: "var(--header-bg)",
          color: "var(--text-primary)",
        }}
      >
        <ThemeProvider>
          <SidebarWrapper />
          <NavbarWrapper />
          <ContentWrapper>{children}</ContentWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
